DELETE {{admin_host}}/delete_category/1
###
GET {{admin_host}}/get_category?pk=1
###
POST {{admin_host}}/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
access-token: {{access-token}}
device-id: {{device-id}}

--WebAppBoundary
Content-Disposition: form-data; name="data"

{"title": "test"}
--WebAppBoundary--
Content-Disposition: form-data; name="file"; filename="VID_20180706_203959.mp4"

< E:\Pictures\VID_20180706_203959.mp4
###