# Generated by Django 2.2.3 on 2019-09-29 14:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0002_auto_20190929_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=2),
        ),
    ]
