# Generated by Django 2.2.3 on 2019-09-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0003_auto_20190929_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='points',
            new_name='point',
        ),
    ]
