# Generated by Django 2.2.3 on 2019-09-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0004_auto_20190929_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='factor',
        ),
        migrations.AddField(
            model_name='mission',
            name='factor_number',
            field=models.CharField(default='hihuih', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='mehrpeyk/date/'),
        ),
    ]
