# Generated by Django 2.2.3 on 2019-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0005_auto_20190929_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='factor_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[(0, 'active'), (1, 'ready'), (2, 'done')], default=0, max_length=31),
        ),
    ]
