# Generated by Django 2.2.3 on 2019-09-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0006_auto_20190929_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[(0, 'active'), (1, 'ready'), (2, 'done')], default='active', max_length=31),
        ),
    ]
