# Generated by Django 2.2.3 on 2019-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0007_auto_20190929_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
