# Generated by Django 2.2.3 on 2019-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0008_mission_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(default=0, max_length=31),
        ),
    ]
