# Generated by Django 2.2.3 on 2019-10-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0010_remove_peyk_moaref'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='name',
            field=models.CharField(default='گل ez53', max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='image',
            field=models.FileField(blank=True, default='https://fyf.tac-cdn.net/images/products/large/BF116-11KM_R.jpg?auto=webp&quality=60', null=True, upload_to='mehrpeyk/date/'),
        ),
    ]
