# Generated by Django 2.2.3 on 2019-10-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0011_auto_20191005_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peyk',
            old_name='verified',
            new_name='active',
        ),
    ]
