# Generated by Django 2.2.3 on 2019-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0012_auto_20191007_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(default=1, max_length=31),
        ),
    ]
