# Generated by Django 2.2.3 on 2019-10-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehrpeyk', '0013_auto_20191007_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='peyk',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
