




POST http://{{host}}/mehrpeyk/sign_up
Content-Type: Application/json
device-id: sdfsdfs3453

{
  "phone": "09015518439",
  "moaref": "09015518440",
  "password": "25808585",
  "vehicle": "نیسان"
}
###
POST http://{{host}}/mehrpeyk/activate
Content-Type: Application/json

{
  "code": "30478"
}
###
POST http://{{host}}/mehrpeyk/login
Content-Type: Application/json

{
  "phone": "09015518439",
  "password": "25808585"
}
###
GET http://{{host}}/mehrpeyk/splash
device-id: sdfsdfs3453
###
POST http://{{host}}/mehrpeyk/add_mission
Content-Type: Application/json
token: {{access-token}}

{
  "number": "6516512"
}
###
POST http://{{host}}/mehrpeyk/end_mission
Content-Type: Application/json
token: {{access-token}}

{
  "id": "15"
}
###
GET http://{{host}}/mehrpeyk/get_mission
token: {{access-token}}
###
POST http://{{host}}/mehrpeyk/start_mission
Content-Type: Application/json
token: {{access-token}}

{
  "id": 15
}
###
POST http://{{host}}/mehrpeyk/update_location
Content-Type: Application/json
token: {{access-token}}

{
  "id": 15,
  "longitude": "25.541655",
  "latitude": "22.541655"
}

###