### CRUD = Create Read Update Delete

GET {{host}}/ping

############# Tables #############

### Ad CRUD
POST {{admin_host}}/ad
Content-Type: application/json

{
  "title": {
    "fa": "category-test16"
  },
  "url": "/test",
  "priority": 0,
  "media_id": 1,
  "mobile_media_id": 2,
  "storage_id": 2,
  "type": "home",
  "settings": {}
}

> res.jssss

###
GET {{admin_host}}/ad

> res.jss

###
PUT {{admin_host}}/ads
Content-Type: application/json

{
  "id": 3,
  "title": {
    "fa": "category-test16"
  },
  "url": "/test",
  "priority": 0,
  "media_id": 150,
  "mobile_media_id": 2,
  "storage_id": 2,
  "type": "home",
  "settings": {}
}
> res.js

### Slider CRUD
POST {{admin_host}}/slider
Content-Type: application/json

{
  "title": {
    "fa": "category-test16"
  },
  "url": "/test",
  "priority": 0,
  "media_id": 150,
  "mobile_media_id": 2,
  "product_id": 2,
  "type": "home"
}

> res.jssss

###
GET {{admin_host}}/slider

> res

###
PUT {{admin_host}}/slider
Content-Type: application/json

{
  "id": 15,
  "title": {
    "fa": "category-test16"
  },
  "url": "/test",
  "priority": 0,
  "media_id": 150,
  "mobile_media_id": 2,
  "product_id": 2,
  "type": "home"
}
> res.js

### Category CRUD
POST {{admin_host}}/category
Content-Type: application/json

{
  "parent_id": null,
  "name": {
    "fa": "category-test16"
  },
  "permalink": "permalink-test19",
  "media_id": null
}

> res.js

###
GET {{admin_host}}/category?id=3

> res.js

###
GET {{admin_host}}/category?b=3


> res.js

###
PUT {{admin_host}}/category
Content-Type: application/json

{
  "id": 216,
  "parent": null,
  "name": {
    "fa": "category-test15"
  },
  "feature_groups": [
    1
  ],
  "permalink": "permalink-test3",
  "media": 1,
  "disable": false
}
> res.js

###
DELETE {{admin_host}}/category?id=54

> res.js

### check prices
POST {{admin_host}}/review_price
Content-Type: application/json

{
  "category_id": 396,
  "tax_type": "has_not",
  "discount_price": 5000,
  "start_price": 0,
  "final_price": 10000,
  "shipping_cost": 1000
}

> res.js


### DateRange CRU
POST {{admin_host}}/date_range
Content-Type: application/json

{
  "title": "جمعه",
  "start_date": 1629455843,
  "end_date": 1629465843
}

> res.js

###
GET {{admin_host}}/date_range

> res.js

###
PUT {{admin_host}}/date_range
Content-Type: application/json

{
  "id": 1,
  "title": "پنجشنبه",
  "start_date": 1629355843,
  "end_date": 1629656843
}

> res.js

### DiscountCode CR, Params: id, storage_id
POST {{admin_host}}/discount_code
Content-Type: application/json

{
  "storage_id": 852,
  "count": 10,
  "len": 6,
  "prefix": "test"
}

> res.js

###
### Post Discount Code
POST {{admin_host}}/discount_code
Content-Type: application/json

{
  "type": 3,
  "username": "09015518439"
}

> res.js

###
GET {{admin_host}}/discount_code?id=5

> res.js

###
### Product CRUD
POST {{admin_host}}/product
Content-Type: application/json

{
  "category_id": 3,
  "type": "service",
  "brand_id": 26,
  "categories": [
    234,
    216
  ],
  "features": [
    {
      "feature_id": 90,
      "feature_value_id": 87,
      "settings": {}
    },
    {
      "feature_id": 89,
      "feature_value_id": 88,
      "settings": {}
    }
  ],
  "review": {
    "chats": [],
    "state": "ready"
  },
  "description": {
    "data": {
      "ar": {},
      "en": {},
      "fa": {
        "items": [
          {
            "key": "description",
            "value": "دیسکریپشن محصول"
          }
        ]
      }
    }
  },
  "media": [
    1184,
    1185,
    1182,
    1183
  ],
  "name": {
    "fa": "کفش ورزشی زنانه Adidas مدل MTS-1",
    "en": "",
    "ar": ""
  },
  "permalink": "testhehe3",
  "settings": {
    "adminNote": "انبار ندارد↵اصلاح اسم محصول",
    "productStatus": 2
  },
  "short_description": {
    "ar": "",
    "en": "",
    "fa": "<p>کفش ورزشی زنانه Adidas مدل MTS-1 - Running</p>↵"
  },
  "tag_groups": [],
  "tags": [
    {
      "tag_id": 159,
      "show": false
    },
    {
      "tag_id": 158,
      "show": false
    },
    {
      "tag_id": 157,
      "show": false
    }
  ],
  "thumbnail_id": 1186
}

> res.js

###
GET {{admin_host}}/product?id=516

> res.js

###
GET {{admin_host}}/product?b=11

> res.js

###
PUT {{admin_host}}/product
Content-Type: application/json

{
  "id": 679,
  "manage": true
}

> res.js

###
PUT {{admin_host}}/product
Content-Type: application/json

{
  "id": 1731,
  "name": {
    "fa": "مرجان مینیاتوری قرمز"
  }
}

> res.js

###
DELETE {{admin_host}}/product?id=54

> res.js

### ProductFeature CRUD
GET {{admin_host}}/product?id=513

> res.js

### Storage CRUD
POST {{admin_host}}/storage
Content-Type: application/json

{
  "available_count": 987,
  "available_count_for_sale": 987,
  "deadline": null,
  "dimensions": {
    "weight": 1500,
    "height": 20,
    "length": 40,
    "width": 26
  },
  "discount_price": 315000,
  "features": [
    {
      "product_feature_id": 628,
      "extra_data": {}
    }
  ],
  "final_price": 338000,
  "invoice_description": {
    "fa": "<p></p>",
    "en": "",
    "ar": ""
  },
  "invoice_title": {
    "fa": "کفش ورزشی زنانه Adidas مدل MTS-1",
    "en": "",
    "ar": ""
  },
  "max_count_for_sale": 3,
  "min_count_alert": 0,
  "product_id": 1285,
  "shipping_cost": 0,
  "start_price": 270000,
  "start_time": 1591004832,
  "supplier_id": 6,
  "tax_type": "has_not",
  "title": {
    "fa": "کفش ورزشی زنانه Adidas مدل MTS-1",
    "en": "",
    "ar": ""
  },
  "vip_prices": []
}

> res.js

###
GET {{admin_host}}/storage?id=516

> res.js

###
GET {{admin_host}}/storage

> res.js

###
PUT {{admin_host}}/storage
Content-Type: application/json

{
  "id": 908,
  "available_count": 4,
  "available_count_for_sale": 3,
  "dimensions": {
    "weight": 5,
    "height": 5,
    "length": 5,
    "width": 5
  },
  "discount_price": 4000,
  "features": [
    {
      "product_feature_id": 29,
      "extra_data": {}
    },
    {
      "product_feature_id": 30,
      "extra_data": {}
    }
  ],
  "final_price": 338000,
  "invoice_description": {
    "fa": "<p></p>",
    "en": "",
    "ar": ""
  },
  "invoice_title": {
    "fa": "گل آلستر بنفشASH",
    "en": "",
    "ar": ""
  },
  "max_count_for_sale": 1,
  "max_shipping_time": 48,
  "min_count_alert": 0,
  "product_id": 303,
  "shipping_cost": null,
  "start_price": 4000,
  "start_time": 1590682463,
  "supplier_id": 5,
  "tax_type": "has_not",
  "title": {
    "fa": "گل آلستر بنفشASH",
    "en": "",
    "ar": ""
  },
  "vip_prices": [],
  "accessories": [
    {
      "accessory_product_id": 1270,
      "accessory_storage_id": 845,
      "discount_price": 2000
    },
    {
      "accessory_product_id": 1277,
      "accessory_storage_id": 845,
      "discount_price": 3000
    }
  ]
}

> res.js

###
DELETE {{admin_host}}/storage?id=54

> res.js

### Feature CRUD
POST {{admin_host}}/feature
Content-Type: application/json

{
  "name": {
    "fa": "2فیچر با اردر"
  },
  "groups": [
    1
  ],
  "type": "text",
  "layout_type": "default",
  "values": [
    {
      "value": {
        "fa": 2
      },
      "settings": {}
    },
    {
      "value": {
        "fa": 1
      },
      "settings": {}
    },
    {
      "value": {
        "fa": 3
      },
      "settings": {}
    }
  ]
}

> res.js

###
GET {{admin_host}}/feature?id=35

> res.js

###
GET {{admin_host}}/feature?b=3

> res.js

###
PUT {{admin_host}}/feature
Content-Type: application/json

{
  "id": 62,
  "name": {
    "fa": "تست مرتب سازی 2"
  },
  "groups": [
    1
  ],
  "type": "selectable",
  "layout_type": "default",
  "values": [
    {
      "value": {
        "fa": 35
      },
      "settings": {}
    },
    {
      "value": {
        "fa": 40
      },
      "settings": {}
    },
    {
      "value": {
        "fa": 45
      },
      "settings": {}
    }
  ]
}

> res.js

###
PATCH {{admin_host}}/feature
Content-Type: application/json

{
  "ids": [
    124,
    123,
    118,
    117
  ]
}

> res.js

###
DELETE {{admin_host}}/feature_value?id=54

> res.js

### FeatureValue CRUD
POST {{admin_host}}/feature_value
Content-Type: application/json

{
  "value": {
    "fa": "سفید"
  },
  "feature_id": 43
}

> res.js

###
GET {{admin_host}}/feature_value?id=9

> res.js

###
GET {{admin_host}}/feature_value

> res.js

###
PUT {{admin_host}}/feature_value
Content-Type: application/json

{
  "id": 2,
  "value": {
    "fa": "یک متن ساختگی پیشفرض برای توضیحات کفش"
  }
}

> res.js

###
DELETE {{admin_host}}/feature_value?id=54

> res.js

### FeatureGroup CRUD
POST {{admin_host}}/feature_group
Content-Type: application/json

{
  "name": {
    "fa": "مشخصات فنی2"
  },
  "category_id": 3,
  "settings": {
    "ui": {
      "show_title": false
    }
  },
  "features": [
    80,
    81,
    82
  ]
}

> res.js

###
GET {{admin_host}}/feature_group?id=1

> res.js

###
GET {{admin_host}}/feature_group?b=1

> res.js

###
PUT {{admin_host}}/feature_group
Content-Type: application/json

{
  "id": 2,
  "name": {
    "fa": "مشخصات فنی"
  },
  "category_id": 3,
  "show_title": true,
  "features": [
    87,
    88,
    84,
    86,
    85,
    89
  ]
}

> res.js

###
DELETE {{admin_host}}/feature_group?id=54

> res.js

### Brand CRUD
POST {{admin_host}}/brand
Content-Type: application/json

{
  "name": {
    "fa": "api-test3",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test3"
}

> res.js

###
GET {{admin_host}}/brand?id=6

> res.js

###
GET {{admin_host}}/brand?b=3&p=1&s=100&o=id&all=true

> res.js

###
GET {{admin_host}}/brand

> res.js

###
PUT {{admin_host}}/brand
Content-Type: application/json

{
  "id": 6,
  "name": {
    "fa": "api-test2",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test2"
}

> res.js

###
DELETE {{admin_host}}/brand?id=6

> res.js

###

### Tag CRUD
POST {{admin_host}}/tag
Content-Type: application/json

{
  "name": {
    "fa": "چای سیاه4",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test55"
}

> res.js

###
GET {{admin_host}}/tag?id=6

> res.js

###
GET {{admin_host}}/tag

> res.js

###
PUT {{admin_host}}/tag
Content-Type: application/json

{
  "id": 93,
  "name": {
    "fa": "api-test2",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test2"
}

> res.js

###
PATCH {{admin_host}}/tag
Content-Type: application/json

{
  "tags": [
    1,
    2,
    3
  ]
}

> res.js

###
DELETE {{admin_host}}/brand?id=6

> res.js

###

### GroupTag CRUD
POST {{admin_host}}/tag_group
Content-Type: application/json

{
  "name": {
    "fa": "'گروه تگ تست'",
    "en": "",
    "ar": ""
  },
  "category_id": 1,
  "tags": [
    1,
    2,
    3,
    4,
    5
  ]
}

> res.js

###
GET {{admin_host}}/tag_group?b=1

> res.js

###
GET {{admin_host}}/tag_group?id=1

> res.js

###
PUT {{admin_host}}/tag_group
Content-Type: application/json

{
  "id": 63,
  "name": {
    "fa": "'گروه تگ تست'",
    "en": "",
    "ar": ""
  },
  "category_id": 1,
  "tags": [
    {
      "tag_id": 1,
      "show": false
    },
    {
      "tag_id": 2,
      "show": true
    }
  ]
}

> res.js

###
DELETE {{admin_host}}/tag_group?id=1

> res.js

###

### Invoice R
GET {{admin_host}}/invoice

> res.js

### Invoice Product
GET {{admin_host}}//invoice_product

> res.js

### Seupplier CRU
POST {{admin_host}}/supplier
Content-Type: application/json

{
  "first_name": "shapoor",
  "last_name": "bagheri",
  "username": "09015618439",
  "phone": "01333003033",
  "shaba": "IR123456789",
  "meli_code": "2580859722",
  "settings": {}
}

> res.js

###
PUT {{admin_host}}/supplier
Content-Type: application/json

{
  "id": 2,
  "first_name": "shapoor",
  "last_name": "bagheri",
  "username": "09015618440",
  "phone": "01333003033",
  "shaba": "IR123456789",
  "meli_code": "2580859722"
}

> res.js

###
GET {{admin_host}}/supplier?id=2

> res.js

###

### Invoice R
GET {{admin_host}}/invoice

> res.js

###

### Media CRUD
POST {{admin_host}}/media
Content-Type: multipart/form-data; boundary=WebAppBoundary
#access-token: {{access-token}}

--WebAppBoundary
Content-Disposition: form-data; name="data"

{"category_id": null, "type": 2, "titles": [{"fa": "نام دسته بندی"}, {"fa": "2نام دسته بندی"}]}
--WebAppBoundary--
Content-Disposition: form-data; name="file"; filename="takh1.png"

< F:\Download\Photos\takh1.png

> res.js

###
GET {{admin_host}}/media?b=3
Accept: application/json

> res.js

###
GET {{admin_host}}/media?id=18
Accept: application/json

> res.js

###
PATCH {{admin_host}}/media
Content-Type: application/json

{
  "id": 18,
  "title": {
    "fa": "test"
  }
}

> res.js

###
DELETE {{admin_host}}/media?id=18

> res.js

###

### TableFilter R
GET {{admin_host}}/table_filter/product

> res.js

###
GET {{admin_host}}/table_filter/media

> res.js

###

############# Views #############

### Roll R
GET {{admin_host}}/roll

> res.js

###

### Search
GET {{admin_host}}/search?type=supplier&q=میلاد

> res.js

###

### Settings
GET {{admin_host}}/settings/box

> res.js

###
GET {{admin_host}}/settings/product

> res.js

###

### Icon
GET {{admin_host}}/icon/feature

> res.js

###

PUT {{admin_host}}/ordering
Content-Type: application/json

{
  "model": "product_feature",
  "ids": [
    551,
    553,
    550,
    552
  ]
}

> res.js

###

PUT {{admin_host}}/ordering
Content-Type: application/json

{
  "model": "category",
  "ids": [
    220,
    216,
    213
  ]
}

> res.js

### Cache Control
GET {{admin_host}}/cache

> res.js

###
DELETE {{admin_host}}/cache/*

> res.js

###
DELETE http://api.mt.com/admin/cache/a?token=ff5294ad781a23c32824ea9adbfc1521f771481cc95aecede421ed65

> res.js

###

OPTIONS https://api.mehrtakhfif.com/basket