### orders: cheap, expensive, best_seller, popular, discount

### box main page
### just available products
GET {{host}}/box/boom-gardi?available=true&orderby=cheap
### support for multiple brand
GET {{host}}/box/boom-gardi?brand=brand1&brand=brand2
### min and max should send together
GET {{host}}/box/boom-gardi?min_price=50000&max_price=100000
###

### features
### get box features
GET {{host}}/features?box=boom-gardi
###get category features
GET {{host}}/features?category=tour-safar
###

### other
GET {{host}}/box_detail/boom-gardi
###
GET {{host}}/category/tour-safar
###
GET {{host}}/tag/cafe
###