GET {{host}}/slider
###
GET {{host}}/special_offer
###
GET {{host}}/special_product
###
GET {{host}}/box_special_product
###
GET {{host}}/best_seller
###
GET {{host}}/box_with_category
###
GET {{host}}/ads
###
GET {{host}}/category
###
GET {{host}}/menu
###
GET {{host}}/get_states
###
GET {{host}}/get_cities/26
###
GET {{host}}/search?q=query

### all box with category
http://localhost/box_with_category
###
http://localhost/box_with_category?box_permalink=boom-gardi
###
GET {{host}}/special_offer