### CRUD = Create Read Update Delete

GET {{host}}/test

############# Tables #############

### Category CRUD
POST {{admin_host}}/category
Content-Type: application/json

{
  "id": 54,
  "parent": null,
  "box_id": 3,
  "features": [
    29,
    43
  ],
  "name": {
    "fa": "category-test15"
  },
  "permalink": "permalink-test3",
  "media": null
}

###
GET {{admin_host}}/category?id=54

###
GET {{admin_host}}/category?b=3

###
PUT {{admin_host}}/category
Content-Type: application/json

{
  "id": 216,
  "parent": null,
  "box_id": 3,
  "name": {
    "fa": "category-test15"
  },
  "feature_groups": [
    1
  ],
  "permalink": "permalink-test3",
  "media": 1
}

###
PUT {{admin_host}}/category
Content-Type: application/json

{
  "id": 171,
  "disable": false
}

###
DELETE {{admin_host}}/category?id=54

### check prices
POST {{admin_host}}/review_price
Content-Type: application/json

{
  "b": 10,
  "tax_type": "from_total_price",
  "discount_price": 20000,
  "start_price": 0,
  "final_price": 10000,
  "shipping_cost": 1000
}

### DiscountCode CR, Params: id, storage_id
POST {{admin_host}}/discount_code
Content-Type: application/json

{
  "storage_id": 3,
  "count": 10,
  "len": 6,
  "prefix": "test"
}
###
### Post Discount Code
POST {{admin_host}}/discount_code
Content-Type: application/json

{
  "type": 3,
  "username": "09015518439"
}

###
GET {{admin_host}}/discount_code?id=5

###
### Product CRUD
POST {{admin_host}}/product
Content-Type: application/json

{
  "box_id": 3,
  "type": "product",
  "brand_id": 26,
  "categories": [
    234,
    216
  ],
  "features": [
    {
      "feature_id": 31,
      "feature_value_id": 87,
      "settings": {}
    },
    {
      "feature_id": 32,
      "feature_value_id": 88,
      "settings": {}
    }
  ],
  "check_review": false,
  "description": {
    "data": {
      "ar": {},
      "en": {},
      "fa": {
        "items": [
          {
            "key": "description",
            "value": "دیسکریپشن محصول"
          }
        ]
      }
    }
  },
  "id": 51,
  "media": [
    1184,
    1185,
    1182,
    1183
  ],
  "name": {
    "fa": "کفش ورزشی زنانه Adidas مدل MTS-1",
    "en": "",
    "ar": ""
  },
  "permalink": "test1019",
  "review": null,
  "settings": {
    "adminNote": "انبار ندارد↵اصلاح اسم محصول",
    "productStatus": 2
  },
  "short_description": {
    "ar": "",
    "en": "",
    "fa": "<p>کفش ورزشی زنانه Adidas مدل MTS-1 - Running</p>↵"
  },
  "tag_groups": [],
  "tags": [
    {
      "tag_id": 159,
      "show": false
    },
    {
      "tag_id": 158,
      "show": false
    },
    {
      "tag_id": 157,
      "show": false
    }
  ],
  "thumbnail_id": 1186
}

###
GET {{admin_host}}/product?id=516

###
GET {{admin_host}}/product?b=11

###
PUT {{admin_host}}/product
Content-Type: application/json

{
  "id": 1237,
  "box_id": 3,
  "type": "product",
  "brand_id": 26,
  "categories": [
    234,
    216
  ],
  "features": [
    {
      "feature_id": 33,
      "feature_value_id": 2,
      "settings": {}
    },
    {
      "feature_id": 34,
      "feature_value_id": 8,
      "settings": {}
    }
  ],
  "check_review": false,
  "description": {
    "data": {
      "ar": {},
      "en": {},
      "fa": {
        "items": [
          {
            "key": "description",
            "value": "دیسکریپشن محصول"
          }
        ]
      }
    }
  },
  "media": [
    1184,
    1185,
    1182,
    1183
  ],
  "name": {
    "fa": "کفش ورزشی زنانه Adidas مدل MTS-1",
    "en": "",
    "ar": ""
  },
  "review": null,
  "settings": {
    "adminNote": "انبار ندارد↵اصلاح اسم محصول",
    "productStatus": 2
  },
  "short_description": {
    "ar": "",
    "en": "",
    "fa": "<p>کفش ورزشی زنانه Adidas مدل MTS-1 - Running</p>↵"
  },
  "tag_groups": [],
  "tags": [
    {
      "tag_id": 159,
      "show": false
    },
    {
      "tag_id": 158,
      "show": false
    },
    {
      "tag_id": 157,
      "show": false
    }
  ],
  "thumbnail_id": 1186
}

###
DELETE {{admin_host}}/product?id=54

### ProductFeature CRUD
GET {{admin_host}}/product?id=513

### Storage CRUD
POST {{admin_host}}/storage
Content-Type: application/json

{
  "available_count": 987,
  "available_count_for_sale": 987,
  "deadline": null,
  "dimensions": {
    "weight": 1500,
    "height": 20,
    "length": 40,
    "width": 26
  },
  "discount_price": 305000,
  "features": [],
  "final_price": 338000,
  "invoice_description": {
    "fa": "<p></p>",
    "en": "",
    "ar": ""
  },
  "invoice_title": {
    "fa": "کفش ورزشی زنانه Adidas مدل MTS-1",
    "en": "",
    "ar": ""
  },
  "max_count_for_sale": 3,
  "min_count_alert": 0,
  "product_id": 51,
  "shipping_cost": 0,
  "start_price": 270000,
  "start_time": 1591004832,
  "supplier_id": 6,
  "tax_type": "has_not",
  "title": {
    "fa": "کفش ورزشی زنانه Adidas مدل MTS-1",
    "en": "",
    "ar": ""
  },
  "vip_prices": []
}

###
GET {{admin_host}}/storage?id=516

###
GET {{admin_host}}/storage

###
PUT {{admin_host}}/storage
Content-Type: application/json

{
  "id": 232,
  "available_count": 4,
  "available_count_for_sale": 3,
  "deadline": null,
  "dimensions": {
    "weight": 5,
    "height": 5,
    "length": 5,
    "width": 5
  },
  "discount_price": 305000,
  "features": [
    {
      "product_feature_id": 29,
      "extra_data": {}
    },
    {
      "product_feature_id": 30,
      "extra_data": {}
    }
  ],
  "final_price": 338000,
  "invoice_description": {
    "fa": "<p></p>",
    "en": "",
    "ar": ""
  },
  "invoice_title": {
    "fa": "گل آلستر بنفشASH",
    "en": "",
    "ar": ""
  },
  "max_count_for_sale": 1,
  "max_shipping_time": 0,
  "min_count_alert": 0,
  "product_id": 303,
  "shipping_cost": null,
  "start_price": 4000,
  "start_time": 1590682463,
  "supplier_id": 5,
  "tax_type": "has_not",
  "title": {
    "fa": "گل آلستر بنفشASH",
    "en": "",
    "ar": ""
  },
  "vip_prices": []
}

###
DELETE {{admin_host}}/storage?id=54

### Feature CRUD
POST {{admin_host}}/feature
Content-Type: application/json

{
  "name": {
    "fa": "2فیچر با اردر"
  },
  "groups": [
    1
  ],
  "type": "text",
  "layout_type": "default",
  "values": [
    {
      "value": {
        "fa": 2
      },
      "settings": {}
    },
    {
      "value": {
        "fa": 1
      },
      "settings": {}
    },
    {
      "value": {
        "fa": 3
      },
      "settings": {}
    }
  ]
}

###
GET {{admin_host}}/feature?id=31

###
GET {{admin_host}}/feature?b=3

###
PUT {{admin_host}}/feature
Content-Type: application/json

{
  "id": 62,
  "name": {
    "fa": "تست مرتب سازی 2"
  },
  "groups": [
    1
  ],
  "type": "selectable",
  "layout_type": "default",
  "values": [
    {
      "value": {
        "fa": 35
      },
      "settings": {}
    },
    {
      "value": {
        "fa": 40
      },
      "settings": {}
    },
    {
      "value": {
        "fa": 45
      },
      "settings": {}
    }
  ]
}

###
PATCH {{admin_host}}/feature
Content-Type: application/json

{
  "ids": [
    124,
    123,
    118,
    117
  ]
}

###
DELETE {{admin_host}}/feature_value?id=54

### FeatureValue CRUD
POST {{admin_host}}/feature_value
Content-Type: application/json

{
  "value": {
    "fa": "سفید"
  },
  "feature_id": 43
}

###
GET {{admin_host}}/feature_value?id=9

###
GET {{admin_host}}/feature_value

###
PUT {{admin_host}}/feature_value
Content-Type: application/json

{
  "id": 64,
  "value": {
    "fa": "یک متن ساختگی پیشفرض برای توضیحات کفش"
  },
  "feature_id": 102
}

###
DELETE {{admin_host}}/feature_value?id=54

### FeatureGroup CRUD
POST {{admin_host}}/feature_group
Content-Type: application/json

{
  "name": {
    "fa": "مشخصات فنی"
  },
  "box_id": 3,
  "show_title": true,
  "features": [
    89,
    88,
    87,
    86,
    85,
    84
  ]
}

###
GET {{admin_host}}/feature_group?id=1

###
GET {{admin_host}}/feature_group?b=1

###
PUT {{admin_host}}/feature_group
Content-Type: application/json

{
  "id": 2,
  "name": {
    "fa": "مشخصات فنی"
  },
  "box_id": 3,
  "show_title": true,
  "features": [
    87,
    88,
    84,
    86,
    85,
    89
  ]
}

###
DELETE {{admin_host}}/feature_group?id=54

### Brand CRUD
POST {{admin_host}}/brand
Content-Type: application/json

{
  "name": {
    "fa": "api-test",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test"
}

###
GET {{admin_host}}/brand?id=6

###
GET {{admin_host}}/brand

###
PUT {{admin_host}}/brand
Content-Type: application/json

{
  "id": 6,
  "name": {
    "fa": "api-test2",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test2"
}

###
DELETE {{admin_host}}/brand?id=6

###

### Tag CRUD
POST {{admin_host}}/tag
Content-Type: application/json

{
  "name": {
    "fa": "api-test",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test"
}

###
GET {{admin_host}}/tag?id=6

###
GET {{admin_host}}/tag

###
PUT {{admin_host}}/tag
Content-Type: application/json

{
  "id": 93,
  "name": {
    "fa": "api-test2",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test2"
}

###
PATCH {{admin_host}}/tag
Content-Type: application/json

{
  "tags": [
    1,
    2,
    3
  ]
}

###
DELETE {{admin_host}}/brand?id=6

###

### GroupTag CRUD
POST {{admin_host}}/tag_group
Content-Type: application/json

{
  "name": {
    "fa": "'گروه تگ تست'",
    "en": "",
    "ar": ""
  },
  "box_id": 1,
  "tags": [
    1,
    2,
    3,
    4,
    5
  ]
}

###
GET {{admin_host}}/tag_group?b=1

###
GET {{admin_host}}/tag_group?id=1

###
PUT {{admin_host}}/tag_group
Content-Type: application/json

{
  "id": 63,
  "name": {
    "fa": "'گروه تگ تست'",
    "en": "",
    "ar": ""
  },
  "box_id": 1,
  "tags": [
    {
      "tag_id": 1,
      "show": false
    },
    {
      "tag_id": 2,
      "show": true
    }
  ]
}

###
DELETE {{admin_host}}/tag_group?id=1

###

### Invoice R
GET {{admin_host}}/invoice

### Invoice Product
GET {{admin_host}}//invoice_product

### Seupplier CRU
POST {{admin_host}}/supplier
Content-Type: application/json

{
  "first_name": "shapoor",
  "last_name": "bagheri",
  "username": "09015618439",
  "phone": "01333003033",
  "shaba": "IR123456789",
  "meli_code": "2580859722"
}

###
PUT {{admin_host}}/supplier
Content-Type: application/json

{
  "id": 2,
  "first_name": "shapoor",
  "last_name": "bagheri",
  "username": "09015618440",
  "phone": "01333003033",
  "shaba": "IR123456789",
  "meli_code": "2580859722"
}

###
GET {{admin_host}}/supplier?id=2

###

### Invoice R
GET {{admin_host}}/invoice

###

### Media CRUD
POST {{admin_host}}/media
Content-Type: multipart/form-data; boundary=WebAppBoundary
access-token: {{access-token}}

--WebAppBoundary
Content-Disposition: form-data; name="data"

{"box_id": 3, "type": 2, "titles": [{"fa": "نام دسته بندی"}, {"fa": "2نام دسته بندی"}]}
--WebAppBoundary--
Content-Disposition: form-data; name="file"; filename="takh1.jpg"

< F:\Download\Photos\takh1.jpg
--WebAppBoundary--
Content-Disposition: form-data; name="file"; filename="takh2.jpg"

< F:\Download\Photos\takh2.jpg

###
GET {{admin_host}}/media?b=3
Accept: application/json

###
GET {{admin_host}}/media?id=18
Accept: application/json

###
PATCH {{admin_host}}/media
Content-Type: application/json

{
  "id": 18,
  "title": {
    "fa": "test"
  }
}

###
DELETE {{admin_host}}/media?id=18

###

### TableFilter R
GET {{admin_host}}/table_filter/product

###
GET {{admin_host}}/table_filter/media

###

############# Views #############

### Roll R
GET {{admin_host}}/roll

###

### Search
GET {{admin_host}}/search?type=supplier&q=میلاد

###

### Settings
GET {{admin_host}}/settings/box

###
GET {{admin_host}}/settings/product

###

### Icon
GET {{admin_host}}/icon/feature

###

POST http://poffice.post.ir/webbarcode/getbarcode.asmx