### CRUD = Create Read Update Delete

GET {{host}}/test

############# Tables #############

### Category CRUD
POST {{admin_host}}/category
Content-Type: application/json

{
  "id": 54,
  "parent": null,
  "box_id": 3,
  "name": {
    "fa": "category-test15"
  },
  "permalink": "permalink-test3",
  "media": null
}
###
GET {{admin_host}}/category?id=54
###
GET {{admin_host}}/category?b=3
###
PUT {{admin_host}}/category
Content-Type: application/json

{
  "id": 54,
  "parent": null,
  "box_id": 3,
  "name": {
    "fa": "category-test15"
  },
  "permalink": "permalink-test3",
  "media": 1
}
###
PUT {{admin_host}}/category
Content-Type: application/json

{
  "id": 171,
  "disable": false
}
###
DELETE {{admin_host}}/category?id=54
###

### Feature CRUD
POST {{admin_host}}/feature
Content-Type: application/json

{
  "name": {
    "fa": "test50"
  },
  "type": "bool",
  "value": [
    {
      "id": 1,
      "name": {
        "ar": "",
        "en": "",
        "fa": "میخواهم"
      }
    },
    {
      "id": 2,
      "name": {
        "ar": "",
        "en": "",
        "fa": "نمیخواهم"
      }
    }
  ],
  "box_id": 3
}

###
GET {{admin_host}}/feature?id=31

###
GET {{admin_host}}/feature?b=3

###
PUT {{admin_host}}/feature
Content-Type: application/json

{
  "id": 31,
  "name": {
    "fa": "test50"
  },
  "type": "multi",
  "value": [
    {
      "id": 1,
      "name": {
        "ar": "",
        "en": "",
        "fa": "میخواهم"
      }
    },
    {
      "id": 2,
      "name": {
        "ar": "",
        "en": "",
        "fa": "نمیخواهم"
      }
    }
  ],
  "box_id": 3
}

###
DELETE {{admin_host}}/feature?id=54

###

### Brand CRUD
POST {{admin_host}}/brand
Content-Type: application/json

{
  "name": {
    "fa": "api-test",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test"
}

###
GET {{admin_host}}/brand?id=6

###
GET {{admin_host}}/brand

###
PUT {{admin_host}}/brand
Content-Type: application/json

{
  "id": 6,
  "name": {
    "fa": "api-test2",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test2"
}

###
DELETE {{admin_host}}/brand?id=6
###

### Tag CRUD
POST {{admin_host}}/tag
Content-Type: application/json

{
  "name": {
    "fa": "api-test",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test"
}

###
GET {{admin_host}}/tag?id=6

###
GET {{admin_host}}/tag

###
PUT {{admin_host}}/tag
Content-Type: application/json

{
  "id": 93,
  "name": {
    "fa": "api-test2",
    "en": "",
    "ar": ""
  },
  "permalink": "api-test2"
}

###
PATCH {{admin_host}}/tag
Content-Type: application/json

{
  "tags": [1, 2, 3]
}
###
DELETE {{admin_host}}/brand?id=6
###

### Invoice R
GET {{admin_host}}/invoice

###

### Seupplier CRU
POST {{admin_host}}/supplier
Content-Type: application/json

{
  "first_name": "shapoor",
  "last_name": "bagheri",
  "username": "09015618439",
  "phone": "01333003033",
  "shaba": "IR123456789",
  "meli_code": "2580859722"
}

###
PUT {{admin_host}}/supplier
Content-Type: application/json

{
  "id": 2,
  "first_name": "shapoor",
  "last_name": "bagheri",
  "username": "09015618440",
  "phone": "01333003033",
  "shaba": "IR123456789",
  "meli_code": "2580859722"
}

###
GET {{admin_host}}/supplier?id=2
###

### Invoice R
GET {{admin_host}}/invoice

###

### Media CRUD
POST {{admin_host}}/media
Content-Type: multipart/form-data; boundary=WebAppBoundary
access-token: {{access-token}}

--WebAppBoundary
Content-Disposition: form-data; name="data"

{"box_id": 3, "type": 2, "titles": [{"fa": "نام دسته بندی"}, {"fa": "2نام دسته بندی"}]}
--WebAppBoundary--
Content-Disposition: form-data; name="file"; filename="takh1.jpg"

< F:\Download\Photos\takh1.jpg
--WebAppBoundary--
Content-Disposition: form-data; name="file"; filename="takh2.jpg"

< F:\Download\Photos\takh2.jpg

###
GET {{admin_host}}/media?b=3
Accept: application/json

###
GET {{admin_host}}/media?id=18
Accept: application/json

###
PATCH {{admin_host}}/media
Content-Type: application/json

{
  "id": 18,
  "title": {
    "fa": "test"
  }
}

###
DELETE {{admin_host}}/media?id=18

###

### TableFilter R
GET {{admin_host}}/table_filter/product

###
GET {{admin_host}}/table_filter/media

###

############# Views #############

### Roll R
GET {{admin_host}}/roll

###

### Search
GET {{admin_host}}/search?type=supplier&q=میلاد

###

### Settings
GET {{admin_host}}/settings/box

###
GET {{admin_host}}/settings/product

###

### Icon
GET {{admin_host}}/icon/feature
###

POST http://poffice.post.ir/webbarcode/getbarcode.asmx