### product
GET {{host}}/product/پودر-زردچوبه

> res.js

###
GET {{host}}/features/بازی-فکری-وستروس-game-of-thrones

> res.js

### related products
GET {{host}}/related_products/بازی-فکری-وستروس-game-of-thrones?p=1&s=3

> res.js

### Comment - type: 1: 'q-a'
GET {{host}}/comment?prp=بازی-فکری-وستروس-game-of-thrones&type=1&s=5&p=1

> res.js

### Comment - type 2: 'rate'
GET {{host}}/comment?prp=بازی-فکری-وستروس-game-of-thrones&type=1&s=5&p=1

> res.js

### Comment replies
GET {{host}}/comment?comment_id=48&s=5&p=1

> res.js

###
DELETE {{host}}/comment?id=45

> res.js

### type 2 rate
POST {{host}}/comment
Content-Type: Application/json

{
  "text": "راضی  بودی؟7",
  "type": 2,
  "product_permalink": "تسسست",
  "rate": 10,
  "satisfied": false
}

> res.js

### type 1 question
POST {{host}}/comment
Content-Type: Application/json

{
  "text": "راضی  بودی؟",
  "type": 1,
  "product_permalink": "تسسست",
  "first_name": "reza",
  "last_name": "babaei"
}

> res.js

### type 1 answer
POST {{host}}/comment
Content-Type: Application/json

{
  "text": "راضی  بودی؟",
  "type": 1,
  "reply_to_id": 10,
  "product_permalink": "تسسست"
}

> res.js










