### Comment
### Available routes:

### product
GET {{host}}/product/پودر-زردچوبه
###
GET {{host}}/features/بازی-فکری-وستروس-game-of-thrones

### related products
GET {{host}}/related_products/p-30?p=1&s=3

### Comment - type: 1: 'q-a'
GET {{host}}/comment?product_id=23&type=1&s=5&p=1
### Comment - type 2: 'rate'
GET {{host}}/comment?product_id=23&type=1&s=5&p=1
### Comment replies
GET {{host}}/comment?comment_id=48&s=5&p=1
###
DELETE {{host}}/comment?id=45
### type 2 rate
POST {{host}}/comment
Content-Type: Application/json

{
	"text": "راضی  بودی؟7",
	"type": 2,
	"product_permalink": "تسسست",
    "rate": 10,
    "satisfied": false
}
### type 1 question
POST {{host}}/comment
Content-Type: Application/json

{
	"text": "راضی  بودی؟",
	"type": 1,
	"product_permalink": "تسسست",
    "first_name": "reza",
    "last_name": "babaei"
}
### type 1 answer
POST {{host}}/comment
Content-Type: Application/json

{
	"text": "راضی  بودی؟",
	"type": 1,
    "reply_to_id": 10,
	"product_permalink": "تسسست"
}
###

http://api.mt.com/test









