### Basket
GET http://{{host}}/basket
###
DELETE http://{{host}}/basket?basket_product_id=16
### add to basket
POST {{host}}/basket
Content-Type: Application/json

{
  "products": [{"id": 266, "count":  2, "features": []}],
  "override": true,
  "add": true
}
###


### get products with list of id
POST {{host}}/product
Content-Type: Application/json

{
	"basket": [{"id": 13, "count": 1}, {"id": 17, "count": 1}, {"id": 18, "count": 1}]
}


### get payment: basket_id, ipg_id: default = 1
GET {{host}}/payment/2

### for ipg
POST {{host}}/callback
Content-Type: Application/json

{
	"OrderId": 102,
	"Description": "this is a test payment"
}

###   all   tax  price_without_tax  discount  final_price  unit_price
###   4000  330        3670           2000        6000        1835