### Basket
GET http://{{host}}/basket

###
DELETE http://{{host}}/basket?basket_product_id=16

### add to basket
POST {{host}}/basket
Content-Type: Application/json

{
  "products": [
    {
      "id": 266,
      "count": 2,
      "features": []
    }
  ],
  "override": true,
  "add": true
}

### DiscountCode
POST {{host}}/discount_code
Content-Type: application/json

{
  "code": "123456"
}

###

### get products with list of id
POST {{host}}/product
Content-Type: Application/json

{
  "basket": [
    {
      "id": 13,
      "count": 1,
      "features": []
    },
    {
      "id": 17,
      "count": 1,
      "features": []
    },
    {
      "id": 18,
      "count": 1,
      "features": []
    }
  ]
}

### get payment: basket_id, ipg_id: default = 1
GET {{host}}/payment/2

### for ipg
POST {{host}}/callback
Content-Type: Application/json

{
  "OrderId": 102,
  "Description": "this is a test payment"
}

### get basket
GET {{host}}/basket?use_session=False

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### get basket from session
GET {{host}}/basket?use_session=True

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### add to basket
POST {{host}}/basket
Content-Type: application/json

{
  "products": [
    {
      "id": 329,
      "count": 3
    }
  ],
  "use_session": false
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### add to basket using session
POST {{host}}/basket
Content-Type: application/json

{
  "products": [
    {
      "storage_id": 329,
      "count": 3
    }
  ],
  "use_session": true
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://api.mt.com/test

###
