### Basket
GET http://{{host}}/basket
###
DELETE http://{{host}}/basket?product_id=4
### add to basket
POST {{host}}/basket
Content-Type: Application/json

{
  "products": [{"id": 1, "count":  5, "fid": 16, "fvid":  2}, {"id": 2, "count":  3}],
  "override": true,
  "add": true
}
###


### get products with list of id
POST {{host}}/get_products
Content-Type: Application/json

{
	"basket": [{"id": 13, "count": 1}, {"id": 17, "count": 1}, {"id": 18, "count": 1}]
}


### get payment: basket_id, ipg_id: default = 1
GET {{host}}/payment/31?ipg_id=1

### for ipg
POST {{host}}/callback
Content-Type: Application/json

{
	"OrderId": 102,
	"Description": "this is a test payment"
}

###