# Generated by Django 2.2.3 on 2019-09-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image'), ('audio', 'audio')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('service', 'service'), ('product', 'product')], max_length=255),
        ),
    ]
