# Generated by Django 2.2.3 on 2019-07-31 18:15

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism',
            name='date2',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourism',
            name='date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
    ]
