# Generated by Django 2.2.3 on 2019-09-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190922_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='product',
        ),
        migrations.AddField(
            model_name='box',
            name='meta_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Storage'),
        ),
        migrations.AddField(
            model_name='tag',
            name='meta_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
