# Generated by Django 2.2.3 on 2019-07-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190731_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
