# Generated by Django 2.2.3 on 2019-09-30 17:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190923_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.State')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
