# Generated by Django 2.2.3 on 2019-07-31 18:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_delete_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
    ]
