# Generated by Django 2.2.3 on 2019-09-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
