# Generated by Django 2.2.3 on 2019-08-10 17:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20190807_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='featuredata',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_condition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
    ]
