# Generated by Django 2.2.3 on 2019-08-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190810_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdetail',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
