# Generated by Django 2.2.3 on 2019-10-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20191004_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[(0, 'active'), (1, 'rejected'), (2, 'paid')], default='active', max_length=100),
        ),
    ]
