# Generated by Django 2.2.3 on 2019-08-18 13:32

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_media_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
