# Generated by Django 2.2.3 on 2019-10-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_basket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='server.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=1698, on_delete=django.db.models.deletion.PROTECT, to='server.City'),
            preserve_default=False,
        ),
    ]
