# Generated by Django 2.2.3 on 2019-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20190818_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='not_accepted_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='special_offer_not_accepted_products', to='server.Storage'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='special_offer_products', to='server.Storage'),
        ),
    ]
