# Generated by Django 2.2.3 on 2019-08-18 17:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20190818_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='value',
        ),
        migrations.AddField(
            model_name='feature',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.feature_value),
        ),
        migrations.DeleteModel(
            name='FeatureData',
        ),
    ]
