# Generated by Django 2.2.3 on 2019-08-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20190819_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
    ]
