# Generated by Django 2.2.3 on 2019-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_remove_media_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
