# Generated by Django 2.2.3 on 2019-08-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_slider_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='server.Box'),
            preserve_default=False,
        ),
    ]
