# Generated by Django 2.2.3 on 2019-10-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_user_is_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_money',
            field=models.IntegerField(default=0, verbose_name='Wallet money'),
        ),
    ]
