# Generated by Django 2.2.3 on 2019-08-21 11:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_product_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='_name',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='foo', default=server.models.multilanguage),
        ),
    ]
