# Generated by Django 2.2.3 on 2019-10-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_remove_user_is_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
