# Generated by Django 2.2.3 on 2019-08-21 11:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20190821_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_name',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
    ]
