# Generated by Django 2.2.3 on 2019-08-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_auto_20190821_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='server.Box'),
            preserve_default=False,
        ),
    ]
