# Generated by Django 2.2.3 on 2019-10-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token_expire',
            field=models.DateTimeField(auto_now_add=True, default='2019-10-08 16:10:55.670185+03:30'),
            preserve_default=False,
        ),
    ]
