# Generated by Django 2.2.3 on 2019-10-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_user_reset_token_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Box'),
        ),
    ]
