# Generated by Django 2.2.3 on 2019-08-25 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-08-24 16:10:28.261969+04:30', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='storage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='storage',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
            preserve_default=False,
        ),
    ]
