# Generated by Django 2.2.3 on 2019-10-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20191010_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image'), ('audio', 'audio'), ('slider', 'slider')], max_length=255),
        ),
    ]
