# Generated by Django 2.2.3 on 2019-10-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20191010_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storage',
            name='available_count',
            field=models.BigIntegerField(default=0, verbose_name='Available count'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='available_count_for_sale',
            field=models.BigIntegerField(default=0, verbose_name='Available count for sale'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='discount_price',
            field=models.BigIntegerField(default=0, verbose_name='Discount price'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='discount_price_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Discount price percent'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='discount_vip_price',
            field=models.BigIntegerField(default=0, verbose_name='Discount vip price'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='discount_vip_price_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Discount vip price percent'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='final_price',
            field=models.BigIntegerField(default=0, verbose_name='Final price'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='start_price',
            field=models.BigIntegerField(default=0, verbose_name='Start price'),
        ),
    ]
