# Generated by Django 2.2.3 on 2019-08-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20190825_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialproducts',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='server.Box'),
            preserve_default=False,
        ),
    ]
