# Generated by Django 2.2.3 on 2019-10-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_auto_20191012_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
