# Generated by Django 2.2.3 on 2019-10-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_user_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='09356987456', max_length=15),
            preserve_default=False,
        ),
    ]
