# Generated by Django 2.2.3 on 2019-10-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='child',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
