# Generated by Django 2.2.3 on 2019-10-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_category_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_child', to='server.Category'),
        ),
    ]
