# Generated by Django 2.2.3 on 2019-08-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_auto_20190825_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
