# Generated by Django 2.2.3 on 2019-09-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_auto_20190825_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='discount_price_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Discount price percent'),
        ),
        migrations.AddField(
            model_name='storage',
            name='discount_vip_price_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Discount vip price percent'),
        ),
    ]
