# Generated by Django 2.2.3 on 2019-10-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_auto_20191016_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='child',
        ),
    ]
