# Generated by Django 2.2.3 on 2019-09-01 01:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20190901_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialproducts',
            name='title',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
    ]
