# Generated by Django 2.2.3 on 2019-09-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_specialoffer_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialProducts',
            new_name='SpecialProduct',
        ),
    ]
