# Generated by Django 2.2.3 on 2019-09-01 10:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_auto_20190901_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='value',
        ),
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.Media'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=server.models.multilanguage),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
