# Generated by Django 2.2.3 on 2019-09-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_auto_20190901_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialproduct',
            old_name='link',
            new_name='url',
        ),
    ]
