# Generated by Django 2.2.3 on 2019-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_auto_20190901_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
