# Generated by Django 2.2.3 on 2019-09-02 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0034_auto_20190901_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.Storage'),
            preserve_default=False,
        ),
    ]
