# Generated by Django 2.2.3 on 2019-09-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_auto_20190902_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialproduct',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Media'),
        ),
    ]
