# Generated by Django 2.2.3 on 2019-09-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0036_auto_20190903_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.PROTECT, related_name='product_thumbnail', to='server.Media', verbose_name='product thumbnail'),
            preserve_default=False,
        ),
    ]
