# Generated by Django 2.2.3 on 2019-09-03 15:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0037_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_thumbnail', to='server.Media'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='title',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=server.models.multilanguage, null=True),
        ),
    ]
