# Generated by Django 2.2.3 on 2019-09-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_auto_20190903_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='product',
        ),
        migrations.CreateModel(
            name='FactorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(default=1)),
                ('tax', models.IntegerField(default=0)),
                ('price', models.BigIntegerField()),
                ('final_price', models.BigIntegerField(verbose_name='Final price')),
                ('discount_price', models.BigIntegerField(default=0, verbose_name='Discount price')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Factor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Product')),
            ],
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Storage')),
            ],
            options={
                'db_table': 'basket_product',
            },
        ),
    ]
