# Generated by Django 2.2.3 on 2019-09-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_auto_20190904_1935'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='factorproduct',
            table='factor_product',
        ),
    ]
