GET {{host}}/test

############### Basket ###############
POST {{host}}/basket
Content-Type: Application/json
admin: True

{
  "products": [
    {
      "id": 17,
      "count": 3
    },
    {
      "id": 18,
      "count": 10
    }
  ]
}

############### Authentication ###############
POST http://{{host}}/login
Content-Type: Application/json

{
  "username": "09129999999",
  "password": "admin"
}
###
POST {{host}}/activate
Content-Type: Application/json

{
  "code": "260375"
}
###

############### User ###############
GET http://{{host}}/get_states
###
GET http://{{host}}/profile

############### Home ###############
GET http://{{host}}/search?q='تور'
###
GET http://{{host}}/slider
###
GET http://{{host}}/special_offer
###
GET http://{{host}}/special_product
###
GET http://{{host}}/all_special_product
###
GET http://{{host}}/menu
charset: utf-8
Content-Type: Application/json
###
GET http://{{host}}/filter?final_price__gte=50000
###
GET http://{{host}}/search?q='تور'
###

POST http://{{host}}/wishlist
Content-Type: Application/json

{
  "type": "admin",
  "notify": false,
  "product_id": "1"

}
###
GET http://{{host}}/buy?basket_id=4
###
POST http://{{host}}/buy
Content-Type: Application/json

{
  "count": "3",
  "description": "this is a test basket",
  "product_id": [1,2]
}
###

